# Site settings
title: CMSIS SVD
description: >-
  Community project for FOSS tools and Easily Accessible SVD Collections.
baseurl: ""
url: "https://cmsis-svd.github.io"
github_username: cmsis-svd

# Build settings
theme: minima

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
